name: Release Gem

on:
  push:
    tags:
      # Only run this workflow when a tag is created that matches the regex
      # pattern below. This will match tags like "v1.0.0" but not "v1.0.0-rc.1".
      # See https://semver.org/ for more information about semantic versioning.
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
      - name: Run tests
        run: bundle exec rspec
      - name: Setup RubyGems
        run: |
          mkdir -p $HOME/.gem
          echo ":github: Bearer ${{secrets.GITHUB_TOKEN}}" >> $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
      - name: Build Gem
        run: gem build germinator.gemspec
      - name: Get Ruby Gem Version
        run: |
          GEM_VERSION=$(ruby -r ./lib/germinator/version.rb -e "puts Germinator::VERSION")
          echo "GEM_VERSION=$GEM_VERSION" >> $GITHUB_ENV
      - name: Publish Gem
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} germinator-${{env.GEM_VERSION}}.gem
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          discussion_category_name: announcements
          generate_release_notes: true
          files: |
            germinator-${{env.GEM_VERSION}}.gem
